name: musiclase_app
description: "Aplicacion para la clases de musica"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  provider: ^6.0.5
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/AppIcon.png
  min_sdk_android: 21